<div style="background:url(Images/topbg_02_01.gif)">
<table width="997" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="48" align="right"><a href="Cn/"><img src="Images/cn.gif" width="69" height="24" /></a></td>
  </tr>
</table>
</div>
<div style="background:url(Images/topbg_02_02.gif)">
<table width="1003" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="603"><!--#include file="Ad4.Asp"--></td>
    <td width="438" height="185" valign="top">
    <table width="438" border="0" cellspacing="0" cellpadding="0" class="margintop20">
      <tr>
        <td height="37" background="Images/t_02_00.gif" class="paddingleft15 c2 bold">Introduction</td>
      </tr>
      <tr>
        <td class="padding5 c2">NFA designs, develops and manufactures a complete line of user-friendly products for the automotive, marine, outdoor and industrial markets. Our diverse products are separated into SIX categories: 1, NFA DC to AC Power Inverters; 2, NFA Power Packs & Jump Starters; 3, 12 Volt Battery Chargers; 4, NFA Cooler and Warmer Box; 5, NFA HID Off-road & Work Lights; 6, NFA Booster Cables. </td>
      </tr>
    </table></td>
  </tr>
</table>
</div>